<?php
// Display all the possible errors...
ini_set('display_errors', 1);
// Strict mode all...
error_reporting(E_ALL | E_STRICT);
// Make constant the variabale...
DEFINE('DB_HOST','127.0.0.1');
DEFINE('DB_USER','root');
DEFINE('DB_PASS','');
DEFINE('DB_BASE','la_db');
// Instantiate the mysqli object...
$dbcon = new MySQLi(DB_HOST, DB_USER, DB_PASS, DB_BASE);
// Check if the connection if work !...
if (mysqli_connect_error()) {
	// Display the error message...
	print mysqli_connect_error();
	unset($dbcon);
} else {
	// Set the unicode format...
	$dbcon->set_charset('utf-8');
}// End of else statement...
?>
